### ISSUE TITLE
Virus?

### ISSUE THREAD

**Issue by OfficialCRUGG** [TASVideos/BizHawk-Prereqs#1]
According to Windows Defender, this is a virus with high risk. "SoftwareBundler:Win32/Prepscram"

**Comment by Invariel** [comment]
![image](https://user-images.githubusercontent.com/76182/52129177-e712bb80-2604-11e9-985e-7e8a699d2a53.png)
is what I get when I ask Windows Defender for more details.

**Comment by tonylukasavage** [comment]
i too am getting blocked by Windows, it thinks the ddownload is a virus

**Comment by Ketris** [comment]
@TASVideos This prereqs "bundle" could (and should) be replaced with a simple script that grabs the latest files off the Microsoft servers, considering it just installs VisualC/.net/DirectX. These individual packages shouldn't be different from your bundle in any way. The ZIP isn't saving any filesize, and is flagged as a virus due to having many installers bundled into one.

**Comment by Knocks83** [comment]
I too get the download blocked by Windows Defender: to be sure i checked th file on VirusTotal, 3 hits on 61. Let's say the file is pretty clean.
[This](https://www.virustotal.com/#/file/18d0b01fe5859289303f3854ecbfe3355d132f95eb30ababe4d4301749ec5b22/detection) is the result if you want to check.

**Comment by OfficialCRUGG** [comment]
If anybody else is having this problem: I haven't fixed this yet, but for me it worked without using the Prereqs Installer. If it doesn't work for you too, try running BizHawk without the Prereqs Installer.

**Comment by littlelum** [comment]
Is it safe to download, then?

**Comment by Ketris** [comment]
It's totally safe, it's just the method used to package them together sets off a bunch of warning flags in antivirus software that make it think it might be a virus.

Many PCs will already have these packages installed anyway, as they're incredibly common, which is why Bizhawk may work fine for you without the prerequisites package. But if you encounter issues in Bizhawk, make sure you have installed them, and it's safe to disable your antivirus to install.
